server:
  port: 8082
spring:
  application:
    name: isiyi-order

eureka:
  client:
    ## 表示自己注册到eureka注册中心
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka # ,http://eureka7002.com:7002/eureka
