server:
  port: 8082
spring:
  application:
    name: isiyi-order

eureka:
  client:
    ## 表示自己注册到eureka注册中心
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
