server:
  port: 3344
spring:
  application:
    name: isiyi-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ash-Shang/isiyi-springcloud-config.git
          search-paths:
            - isiyi-springcloud-config
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka