server:
  port: 9527
spring:
  application:
    name: isiyi-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ISIYI-PAYMENT #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8081   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/findOne/**   #断言,路径相匹配的进行路由

#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: isiyi-gateway9527
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
