server:
  port: 84


spring:
  application:
    name: isiyi-consumer-order84
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

service-url:
  nacos-user-service: http://isiyi-payment-provider